name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH on runner
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

    - name: Copy docker-compose to VPS
      uses: appleboy/scp-action@master
      with:
        host:     ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USER }}
        key:      ${{ secrets.SSH_PRIVATE_KEY }}
        port:     22
        source:   "game_platform_backend/docker-compose.yml"
        target:   "/home/root/projects/hasset_games/game_platform_backend"

    - name: SSH Commands
      uses: appleboy/ssh-action@master
      with:
        host:     ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USER }}
        key:      ${{ secrets.SSH_PRIVATE_KEY }}
        port:     22
        script: |
          # Trust GitHub for remote cloning
          mkdir -p ~/.ssh
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

          cd /root/projects
          if [ ! -d "hasset_games" ]; then
            git clone --branch main git@github.com:abiywondimu5758/Hasset-games.git
          else
            cd hasset_games
            git pull origin main
          fi

          cd game_platform_backend
          [ -f package.json ] || (echo "Error: package.json not found!" && exit 1)
          npm install
          sudo docker-compose up -d --build
