name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH to VPS and Deploy
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "game_platform_backend/docker-compose.yml"
        target: "/home/root/projects/hasset_games/game_platform_backend"
    - name: SSH Commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Navigate to the projects directory
          cd /root/projects
          
          # Clone the repo if not present, or pull latest changes
          if [ ! -d "hasset_games" ]; then
            git clone --branch main git@github.com:abiywondimu5758/Hasset-games.git
          else
            cd hasset_games
            git pull origin main
          fi
          
          # Navigate to game_platform_backend
          cd game_platform_backend
          
          # Check if package.json exists
          if [ ! -f "package.json" ]; then
            echo "Error: package.json not found!"
            exit 1
          fi
          
          # Install Node.js dependencies
          npm install
          
          # Run Docker Compose to build and deploy the game_platform_backend
          sudo docker-compose up -d --build
